/*
 * This source file was generated by the Gradle 'init' task
 */
package com.ndgndg91

import com.ndgndg91.behavior.fly.FlyRocketPowered
import com.ndgndg91.duck.MallardDuck
import com.ndgndg91.duck.ModelDuck


fun main() {
    val mallard = MallardDuck()
    mallard.performQuack()
    mallard.performFly()

    val model = ModelDuck()
    model.performFly()
    model.setFlyBehavior(FlyRocketPowered())
    model.performFly()
}
